/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import com.digi.xbee.api.RemoteXBeeDevice;
import com.digi.xbee.api.XBeeDevice;
import com.digi.xbee.api.exceptions.XBeeException;
import com.digi.xbee.api.listeners.IDataReceiveListener;
import com.digi.xbee.api.models.XBee64BitAddress;
import com.digi.xbee.api.models.XBeeMessage;
import gnu.io.CommPortIdentifier;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.List;
import java.util.StringTokenizer;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Rafael
 */
public class ConexaoFrame extends javax.swing.JFrame {

    private MainApp mainApp;
    private DefaultTableModel modelProdutos;
    public String envia;
    private static final String PORT = "COM5";
    // TODO Replace with the baud rate of your sender module.  
    private static final int BAUD_RATE = 9600;
    XBeeDevice zigBeeDevice = new XBeeDevice(PORT, BAUD_RATE);
    private IDataReceiveListener listenner;
    private Calendar c = Calendar.getInstance();
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    private String dataHora;
    public static MonitorZig monitorZig;
    private static final String NOMETHREAD = "Verifica Xbee";

    public ConexaoFrame() {
        initComponents();
        ImageIcon icone = new ImageIcon(getClass().getResource("/Img/icone.png"));
        setIconImage(icone.getImage());
        setLocationRelativeTo(null);
        init();
//        this.monitorZig = new MonitorZig("Monitoramento de Xbee",this);
    }

    // inicializa com construtor, esse metedo inicialza todos as instancia de objs
    private void init() {

        this.mainApp = new MainApp(getZigBeeDevice());

        DefaultCaret caret = (DefaultCaret) taDados.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * Realiza o cálculo de checksum para um texto qualquer.
     *
     * @param texto uma string
     * @return o cálculo do checksum em forma numérica.
     */
    public static String calculaCheckSumPara(String texto) {
        char[] chars = texto.toCharArray();
        long resultTemp = chars[0];
        for (int i = 1; i < chars.length; i++) {
            resultTemp ^= chars[i];
        }
        String dado = Long.toHexString(resultTemp).toUpperCase();
        StringBuffer buffer = new StringBuffer(dado);
        if (dado.length() == 1) {
            buffer.insert(0, "0");
        }

        return buffer.toString();
    }
//    public static String calculaCheckSumHexPara(String texto) {
//        final int QUANTIDE_MINIMA_DIGITOS = 2;
//        
//        if (StringUtils.isEmpty(texto)) {
//            throw new IllegalArgumentException("Empty String");
//        }
//        
//        return converteIntegerToHex(calculaCheckSumPara(texto), QUANTIDE_MINIMA_DIGITOS);
//    }
//    
//     public static String converteIntegerToHex(Long l, int quantideMinimaDigitos) {
//        return StringUtils.leftPad(Long.toHexString(l), quantideMinimaDigitos, '0').toUpperCase();
//    }
    //Remover itens da tabela 

    private void clearTable() {

        DefaultTableModel model = (DefaultTableModel) this.tableProdutos.getModel();

        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        model.setRowCount(rows);
    }

    private void insertInTable(List<RemoteXBeeDevice> remotes) {
        //Busca os dados e insere na tabela
        DefaultTableModel model = (DefaultTableModel) this.tableProdutos.getModel();

        remotes.forEach(remote -> {

            model.insertRow(this.tableProdutos.getRowCount(), new Object[]{
                new String(remote.getNodeID()),
                new String(remote.get64BitAddress().toString()),
                new String(remote.get16BitAddress().toString()),});
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btnEnviaBrod = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDados = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDados1 = new javax.swing.JTextArea();
        btnSair = new javax.swing.JToggleButton();
        btnEnviaUni = new javax.swing.JToggleButton();
        HIgh = new javax.swing.JLabel();
        tfAlto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfBaixo = new javax.swing.JTextField();
        checkSum = new javax.swing.JCheckBox();
        btClearTable = new javax.swing.JButton();
        CkLimpar = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        textoDelay = new javax.swing.JTextField();
        JAbas = new javax.swing.JTabbedPane();
        Patio = new javax.swing.JPanel();
        btnZig3P0 = new javax.swing.JToggleButton();
        btnZig3P1 = new javax.swing.JToggleButton();
        btnZig3P2 = new javax.swing.JToggleButton();
        btnZIG4P2 = new javax.swing.JToggleButton();
        btnZIG4P1 = new javax.swing.JToggleButton();
        btnZIG6P0 = new javax.swing.JToggleButton();
        btnZIG6P1 = new javax.swing.JToggleButton();
        btnZIG6P2 = new javax.swing.JToggleButton();
        Entrada = new javax.swing.JPanel();
        btnZig3t = new javax.swing.JToggleButton();
        btnZig34 = new javax.swing.JToggleButton();
        btnZig64 = new javax.swing.JToggleButton();
        btnInicio = new javax.swing.JToggleButton();
        btnIPDA = new javax.swing.JToggleButton();
        btnFin = new javax.swing.JToggleButton();
        Saida = new javax.swing.JPanel();
        btnZig36 = new javax.swing.JToggleButton();
        btnZig35 = new javax.swing.JToggleButton();
        btnZig65 = new javax.swing.JToggleButton();
        btnZig66 = new javax.swing.JToggleButton();
        btnZig3k = new javax.swing.JToggleButton();
        btnSet1 = new javax.swing.JToggleButton();
        CCT = new javax.swing.JPanel();
        btnCanaPicada = new javax.swing.JToggleButton();
        brnCctAut = new javax.swing.JToggleButton();
        brnManuTransb = new javax.swing.JToggleButton();
        cctManCoor = new javax.swing.JToggleButton();
        btnTrator = new javax.swing.JToggleButton();
        btnTCJ = new javax.swing.JToggleButton();
        btnCCJ = new javax.swing.JToggleButton();
        btnTJ = new javax.swing.JToggleButton();
        CicloCaminhao = new javax.swing.JPanel();
        btnCC = new javax.swing.JToggleButton();
        btnTicket = new javax.swing.JToggleButton();
        btnBV = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("Importação TXT");
        fileChooser.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMULADOR MODO API - SOLINFTEC");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "HIGH", "LOW"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProdutos.setName("tabela"); // NOI18N
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 38, 390, 356));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Dispositivos Encontrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 4, 240, 28));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Search_24x24.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 299, 244, 38));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Nome :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 44, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Logs :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 84, 36, -1));

        tfNome.setEditable(false);
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 38, 123, -1));

        btnEnviaBrod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Send_24x24.png"))); // NOI18N
        btnEnviaBrod.setText("Envio Brodcast");
        btnEnviaBrod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviaBrodActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviaBrod, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 98, 244, 42));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete_24x24.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 201, 244, 38));

        taDados.setEditable(false);
        taDados.setColumns(20);
        taDados.setLineWrap(true);
        taDados.setRows(5);
        jScrollPane2.setViewportView(taDados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 80, 640, 308));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Enviar Dados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        taDados1.setColumns(20);
        taDados1.setLineWrap(true);
        taDados1.setRows(5);
        taDados1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nenhum(evt);
            }
        });
        jScrollPane3.setViewportView(taDados1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 445, 681, 210));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cancel_24x24.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 245, 244, 38));

        btnEnviaUni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Send_24x24.png"))); // NOI18N
        btnEnviaUni.setText("Envio Unicast");
        btnEnviaUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviaUniActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviaUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 151, 244, 38));

        HIgh.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        HIgh.setText("High :");
        getContentPane().add(HIgh, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 44, -1, -1));

        tfAlto.setEditable(false);
        tfAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAltoActionPerformed(evt);
            }
        });
        getContentPane().add(tfAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 38, 136, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Low :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 44, -1, -1));

        tfBaixo.setEditable(false);
        getContentPane().add(tfBaixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 38, 180, -1));

        checkSum.setSelected(true);
        checkSum.setText("checksum");
        getContentPane().add(checkSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 410, -1, -1));

        btClearTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Remove_24x24.png"))); // NOI18N
        btClearTable.setText("Limpar logs");
        btClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearTableActionPerformed(evt);
            }
        });
        getContentPane().add(btClearTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 343, 244, 42));

        CkLimpar.setText("Limpar apos envio");
        CkLimpar.setActionCommand("Limpar após envio");
        getContentPane().add(CkLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 410, 130, -1));

        jLabel6.setText("Delay:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 414, -1, -1));

        textoDelay.setText("0");
        getContentPane().add(textoDelay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 60, -1));

        JAbas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "COMANDOS MAG 100", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        JAbas.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        Patio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnZig3P0.setText("ZIG 3P,0");
        btnZig3P0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig3P0ActionPerformed(evt);
            }
        });
        Patio.add(btnZig3P0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 132, 60));

        btnZig3P1.setText("ZIG 3P,1");
        btnZig3P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig3P1ActionPerformed(evt);
            }
        });
        Patio.add(btnZig3P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 132, 60));

        btnZig3P2.setText("ZIG 3P,2");
        btnZig3P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig3P2ActionPerformed(evt);
            }
        });
        Patio.add(btnZig3P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 132, 60));

        btnZIG4P2.setText("ZIG 4P,2");
        btnZIG4P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZIG4P2ActionPerformed(evt);
            }
        });
        Patio.add(btnZIG4P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 132, 60));

        btnZIG4P1.setText("ZIG 4P,1");
        btnZIG4P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZIG4P1ActionPerformed(evt);
            }
        });
        Patio.add(btnZIG4P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 132, 60));

        btnZIG6P0.setText("ZIG 6P,0");
        btnZIG6P0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZIG6P0ActionPerformed(evt);
            }
        });
        Patio.add(btnZIG6P0, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 132, 60));

        btnZIG6P1.setText("ZIG 6P,1");
        btnZIG6P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZIG6P1ActionPerformed(evt);
            }
        });
        Patio.add(btnZIG6P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 132, 60));

        btnZIG6P2.setText("ZIG 6P,2");
        btnZIG6P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZIG6P2ActionPerformed(evt);
            }
        });
        Patio.add(btnZIG6P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 132, 60));

        JAbas.addTab("Patio", Patio);

        Entrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnZig3t.setText("ZIG 3T");
        btnZig3t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig3tActionPerformed(evt);
            }
        });
        Entrada.add(btnZig3t, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 132, 60));

        btnZig34.setText("ZIG 34");
        btnZig34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig34ActionPerformed(evt);
            }
        });
        Entrada.add(btnZig34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 132, 60));

        btnZig64.setText("ZIG 64");
        btnZig64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig64ActionPerformed(evt);
            }
        });
        Entrada.add(btnZig64, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 132, 60));

        btnInicio.setText("INICIO");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        Entrada.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 132, 60));

        btnIPDA.setText("IPDA");
        btnIPDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIPDAActionPerformed(evt);
            }
        });
        Entrada.add(btnIPDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 132, 60));

        btnFin.setText("FIN");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        Entrada.add(btnFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 132, 60));

        JAbas.addTab("Entrada", Entrada);

        Saida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnZig36.setText("ZIG 36");
        btnZig36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig36ActionPerformed(evt);
            }
        });
        Saida.add(btnZig36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 132, 60));

        btnZig35.setText("ZIG 35");
        btnZig35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig35ActionPerformed(evt);
            }
        });
        Saida.add(btnZig35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 132, 60));

        btnZig65.setText("ZIG 65");
        btnZig65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig65ActionPerformed(evt);
            }
        });
        Saida.add(btnZig65, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 132, 60));

        btnZig66.setText("ZIG 66");
        btnZig66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig66ActionPerformed(evt);
            }
        });
        Saida.add(btnZig66, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 130, 62));

        btnZig3k.setText("ZIG 3K");
        btnZig3k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZig3kActionPerformed(evt);
            }
        });
        Saida.add(btnZig3k, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 132, 60));

        btnSet1.setText("SET1");
        btnSet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSet1ActionPerformed(evt);
            }
        });
        Saida.add(btnSet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 132, 60));

        JAbas.addTab("Saida", Saida);

        CCT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCanaPicada.setText("CANA PICADA");
        btnCanaPicada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanaPicadaActionPerformed(evt);
            }
        });
        CCT.add(btnCanaPicada, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 120, 60));

        brnCctAut.setText("CCT AUTOM.");
        brnCctAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCctAutActionPerformed(evt);
            }
        });
        CCT.add(brnCctAut, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, 120, 60));

        brnManuTransb.setText("CCT MAN TRANB");
        brnManuTransb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnManuTransbActionPerformed(evt);
            }
        });
        CCT.add(brnManuTransb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 60));

        cctManCoor.setText("CCT MAN COORD");
        cctManCoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cctManCoorActionPerformed(evt);
            }
        });
        CCT.add(cctManCoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 93, 130, 60));

        btnTrator.setText("TRATOR - JULIETA");
        btnTrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratorActionPerformed(evt);
            }
        });
        CCT.add(btnTrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 15, 300, 30));
        btnTrator.getAccessibleContext().setAccessibleName("TRAT- JUL");

        btnTCJ.setText("TRATOR CARREGADERA-JULIETA");
        btnTCJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTCJActionPerformed(evt);
            }
        });
        CCT.add(btnTCJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 300, 30));

        btnCCJ.setText("CAMINHÃO-CARREGADORA-JULIETA");
        btnCCJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCJActionPerformed(evt);
            }
        });
        CCT.add(btnCCJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 300, -1));

        btnTJ.setText("TRATOR - JULIETA");
        btnTJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTJActionPerformed(evt);
            }
        });
        CCT.add(btnTJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 300, 30));

        JAbas.addTab("CCT", CCT);

        CicloCaminhao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCC.setText("CICLO DE CAMINHÃO");
        btnCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCActionPerformed(evt);
            }
        });
        CicloCaminhao.add(btnCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 60));

        btnTicket.setText("TICKET");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        CicloCaminhao.add(btnTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 150, 60));

        btnBV.setText("BATE VOLTA");
        btnBV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBVActionPerformed(evt);
            }
        });
        CicloCaminhao.add(btnBV, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 10, 150, 60));

        JAbas.addTab("Ciclo Caminhão", CicloCaminhao);

        getContentPane().add(JAbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 448, -1, 210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LogoSGIB.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 280, 70));

        jMenu1.setText("Arquivo");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Importar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ferramentas");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Configurar Xbee (AP)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Confugurações Gerais Xbee");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Calculadora de Checksum");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Codigos Zig");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja realmente sair?", "Solinftec",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
//
    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
        if (evt.getClickCount() == 2) {
            DefaultTableModel model = (DefaultTableModel) this.tableProdutos.getModel();
            int selectedRow = tableProdutos.getSelectedRow();

            tfNome.setText(model.getValueAt(selectedRow, 0).toString());
            tfAlto.setText(model.getValueAt(selectedRow, 1).toString());
            tfBaixo.setText(model.getValueAt(selectedRow, 2).toString());
        }
    }//GEN-LAST:event_tableProdutosMouseClicked
    public void inicia(String texto) {
//        taDados.append(texto);
        taDados.setText(texto);
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {

            if (mainApp.getxBee() == null) {
                throw new Exception("Conexão com ZigBee não foi inicializada!");
            }
            if (!mainApp.getxBee().isOpen()) {
                throw new Exception("Conexão com ZigBee não foi inicializada!");
            }

            //conexao esta aberta
            List<RemoteXBeeDevice> listaZigBees = new LocalizaDispositivo(mainApp.getxBee()).getAllRemoteDev();

            this.clearTable();

            this.insertInTable(listaZigBees);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
        taDados.append("Busca finalizada !\n");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        ConfgXbee xb = new ConfgXbee(this);
        xb.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        taDados.setText("");
        taDados1.setText("");
        tfNome.setText("");
        tfAlto.setText("");
        tfBaixo.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviaBrodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviaBrodActionPerformed

        new Thread(new Runnable() {
            @Override
            public void run() {

                int delay = Integer.parseInt(textoDelay.getText());
                String textoAll;
                if (taDados1.getSelectedText() == null) {
                    textoAll = taDados1.getText();
                } else {
                    textoAll = taDados1.getSelectedText();
                }

                StringTokenizer st = new StringTokenizer(textoAll, "\n");

                if (CkLimpar.isSelected()) {
                    taDados1.setText("");
                }

                while (st.hasMoreTokens()) {

                    String texto = st.nextToken();

                    if (checkSum.isSelected() && !texto.contains("FIN") && !texto.contains("INICIO") && !texto.contains("IPDA")) {

                        texto = texto + ",";
                        texto = texto + calculaCheckSumPara(texto) + '\n';
                    } else {
                        texto = texto + '\n';
                    }
                    c = Calendar.getInstance();
                    dataHora = ("[" + sdf.format(c.getTime()) + "] - ");

                    System.out.println("Send: " + texto);
                    byte[] dataToSend = texto.getBytes();

                    try {

                        mainApp.getxBee().sendBroadcastData(dataToSend);
                        texto = dataHora + texto;
                        taDados.append("Enviado broadcast: " + texto + "\n");

                    } catch (XBeeException ex) {
                        Logger.getLogger(ConexaoFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        Thread.sleep(delay);
                    } catch (InterruptedException ex) {

                    }

                }

            }
        }).start();


    }//GEN-LAST:event_btnEnviaBrodActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja realmente sair?", "Solinftec",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();
            try {
                taDados1.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    private void envia() {
        new Thread(new Runnable() {
            @Override
            public void run() {

                String textoAll = "ZIG35,11976,13A200,415718C2,0,1,0000000400,0000000405,0000000000,2";
                StringTokenizer st = new StringTokenizer(textoAll, "\n");

                while (st.hasMoreTokens()) {

                    String texto = st.nextToken();

                    dataHora = ("[" + sdf.format(c.getTime()) + "] - ");

                    System.out.println("Send: " + texto);
                    byte[] dataToSend = texto.getBytes();

                    try {

                        RemoteXBeeDevice remoteDevice = new RemoteXBeeDevice(mainApp.getxBee(), new XBee64BitAddress(tfAlto.getText().toUpperCase()));

                        if (remoteDevice != null) {

                            mainApp.getxBee().sendData(remoteDevice, dataToSend);
                            texto = dataHora + texto;
                            
                            taDados.append("Enviado unicast: " + texto + "\n");
                        }

                    } catch (XBeeException ex) {
                        Logger.getLogger(ConexaoFrame.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("Erro");
                    }

                }

            }
        }).start();
    }
    private void btnEnviaUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviaUniActionPerformed

        new Thread(new Runnable() {
            @Override
            public void run() {

                int delay = Integer.parseInt(textoDelay.getText());
                String textoAll;
                if (taDados1.getSelectedText() == null) {
                    textoAll = taDados1.getText();
                } else {
                    textoAll = taDados1.getSelectedText();
                }
                StringTokenizer st = new StringTokenizer(textoAll, "\n");

                if (CkLimpar.isSelected()) {
                    taDados1.setText("");
                }

                while (st.hasMoreTokens()) {

                    String texto = st.nextToken();

                   if (checkSum.isSelected() && !texto.contains("FIN") && !texto.contains("INICIO") && !texto.contains("IPDA")) {

                        texto = texto + ",";
                        texto = texto + calculaCheckSumPara(texto) + '\n';
                    } else {
                        texto = texto + '\n';
                    }
                    c = Calendar.getInstance();
                    dataHora = ("[" + sdf.format(c.getTime()) + "] - ");

                    System.out.println("Send: " + texto);
                    byte[] dataToSend = texto.getBytes();

                    try {

                        RemoteXBeeDevice remoteDevice = new RemoteXBeeDevice(mainApp.getxBee(), new XBee64BitAddress(tfAlto.getText().toUpperCase()));

                        if (remoteDevice != null) {

                            mainApp.getxBee().sendData(remoteDevice, dataToSend);
                            texto = dataHora + texto;
                            taDados.append("Enviado unicast: " + texto + "\n");
                        }

                    } catch (XBeeException ex) {
                        Logger.getLogger(ConexaoFrame.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("Erro");
                    }

                    try {
                        Thread.sleep(delay);
                    } catch (InterruptedException ex) {

                    }

                }

            }
        }).start();


    }//GEN-LAST:event_btnEnviaUniActionPerformed

    private void tfAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAltoActionPerformed

    private void btClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearTableActionPerformed

        taDados.setText("");
    }//GEN-LAST:event_btClearTableActionPerformed

    private void nenhum(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nenhum
    }//GEN-LAST:event_nenhum

    private void btnZig3tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig3tActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG3T,141100,13A200,4093E672,0,,,5,0000139635,0000036281,0000000000,2");
    }//GEN-LAST:event_btnZig3tActionPerformed

    private void btnZig34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig34ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG34,54058,13A200,4093D0FD,0,,,5,0000036236,0000036279,0000000000,2");
    }//GEN-LAST:event_btnZig34ActionPerformed

    private void btnZig64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig64ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG64,529,13A200,407B0A55,0000001010,0000002020,0,258684");
    }//GEN-LAST:event_btnZig64ActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        taDados1.setText("INICIO");
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnIPDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIPDAActionPerformed
        // TODO add your handling code here:
        String alto;
        alto = tfAlto.getText();
        String baixo;
        baixo = tfBaixo.getText();

        taDados1.setText("IPDA," + alto + "," + baixo);
    }//GEN-LAST:event_btnIPDAActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        // TODO add your handling code here:
        taDados1.setText("FIN,");
    }//GEN-LAST:event_btnFinActionPerformed

    private void btnSet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSet1ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("SET1J0000054070100001396511000000000012");
    }//GEN-LAST:event_btnSet1ActionPerformed

    private void btnZig35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig35ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG35,11976,13A200,415718C2,0,1,0000000400,0000000405,0000000000,2"
                + "");
    }//GEN-LAST:event_btnZig35ActionPerformed

    private void btnZig36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig36ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG36,11976,13A200415718C2,FFFE,0,1,0000000400,0000000405,0000000000,2");
    }//GEN-LAST:event_btnZig36ActionPerformed

    private void btnZig65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig65ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG65,11976,13A200415718C2,FFFE,0000000400,0000000405,1,1234");
    }//GEN-LAST:event_btnZig65ActionPerformed

    private void btnZig66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig66ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG66,11976,13A200415718C2,FFFE,0000000400,0000000405,1,1234");
    }//GEN-LAST:event_btnZig66ActionPerformed

    private void btnZig3kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig3kActionPerformed
        taDados1.setText("ZIG3K,11976,1");
    }//GEN-LAST:event_btnZig3kActionPerformed

    private void btnCanaPicadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanaPicadaActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,20,01,2345,01,16014,190810,181153,01,3,4,4,4,N,01,5,01,4,01,7,01,5,01,5,01,7,01,08,01,01,1");
    }//GEN-LAST:event_btnCanaPicadaActionPerformed

    private void brnCctAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCctAutActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,21,1234,9898,ZIG20,2580,0011,2121,102534,110610,5151,8989,2113.2137,05026.8658,2,10,3,2");
    }//GEN-LAST:event_brnCctAutActionPerformed

    private void brnManuTransbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnManuTransbActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,24,336,59,ZIG24,0000000098,66,59,165,258,3,36,0");
    }//GEN-LAST:event_brnManuTransbActionPerformed

    private void cctManCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cctManCoorActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,25,452,1157,ZIG43,0000003332,333333,2222,22,131458,210212");
    }//GEN-LAST:event_cctManCoorActionPerformed

    private void btnTratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratorActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,27,6425,1166,ZIG27,0000007474,4587,1168,31,25,190412,131429");
    }//GEN-LAST:event_btnTratorActionPerformed

    private void btnTCJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTCJActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,26,6425,1166,ZIG26,0000006464,4587,1168,102534,100310,1234,789,2112.28896,05026.17630");
    }//GEN-LAST:event_btnTCJActionPerformed

    private void btnCCJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCJActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,28,6425,1166,ZIG28,0000002030,102534,100310,1234,789,2112.28896,05026.17630");
    }//GEN-LAST:event_btnCCJActionPerformed

    private void btnTJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTJActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,27,6425,1166,ZIG27,0000007474,4587,1168,31,25,190412,131429");
    }//GEN-LAST:event_btnTJActionPerformed

    private void btnCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,23,12,1,0.4,100510,290113");
    }//GEN-LAST:event_btnCCActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,81,11,1157,0000001010,1,4,310113185958110000011111");
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnBVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBVActionPerformed
        // TODO add your handling code here:
        taDados1.setText("KIJO50,29,101463,190,191301,200213,2112.47604,04748.07723");
    }//GEN-LAST:event_btnBVActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CalculadoraCS cs = new CalculadoraCS();
        cs.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnZig3P0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig3P0ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG3P,0,1321,13A200,40BE609D,2111.03870,04838.98455,0000000814,0000000766");
    }//GEN-LAST:event_btnZig3P0ActionPerformed

    private void btnZig3P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig3P1ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG3P,1,5523,13A200,40475D5A,2112.29020,05026.17759,0000011111,0000002222");
    }//GEN-LAST:event_btnZig3P1ActionPerformed

    private void btnZig3P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZig3P2ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG3P,2,5523,13A200,40475D5A,2112.28947,05026.17715,0000011111,0000002222");
    }//GEN-LAST:event_btnZig3P2ActionPerformed

    private void btnZIG4P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZIG4P2ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG4P,2,0,13A200,40473275,,,,,,,");
    }//GEN-LAST:event_btnZIG4P2ActionPerformed

    private void btnZIG4P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZIG4P1ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG4P,1,13A200,41675D5F,700916500360,100753100752");
    }//GEN-LAST:event_btnZIG4P1ActionPerformed

    private void btnZIG6P0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZIG6P0ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG6P,0,5523,13A200,40475D5A,2112.28953,05026.17688,0000011111,0000002222");
    }//GEN-LAST:event_btnZIG6P0ActionPerformed

    private void btnZIG6P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZIG6P1ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG6P,1,5523,13A200,40475D5A,2112.28953,05026.17688,0000011111,0000002222");
    }//GEN-LAST:event_btnZIG6P1ActionPerformed

    private void btnZIG6P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZIG6P2ActionPerformed
        // TODO add your handling code here:
        taDados1.setText("ZIG6P,2,5523,13A200,40475D5A,2112.28953,05026.17688,0000011111,0000002222");
    }//GEN-LAST:event_btnZIG6P2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Zig c = new Zig();
        c.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        Atualizar();
//        listPorts();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new ConfgModoTrabalho(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexaoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CCT;
    private javax.swing.JPanel CicloCaminhao;
    private javax.swing.JCheckBox CkLimpar;
    private javax.swing.JPanel Entrada;
    private javax.swing.JLabel HIgh;
    private javax.swing.JTabbedPane JAbas;
    private javax.swing.JPanel Patio;
    private javax.swing.JPanel Saida;
    private javax.swing.JToggleButton brnCctAut;
    private javax.swing.JToggleButton brnManuTransb;
    private javax.swing.JButton btClearTable;
    private javax.swing.JToggleButton btnBV;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnCC;
    private javax.swing.JToggleButton btnCCJ;
    private javax.swing.JToggleButton btnCanaPicada;
    private javax.swing.JToggleButton btnEnviaBrod;
    private javax.swing.JToggleButton btnEnviaUni;
    private javax.swing.JToggleButton btnFin;
    private javax.swing.JToggleButton btnIPDA;
    private javax.swing.JToggleButton btnInicio;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JToggleButton btnSet1;
    private javax.swing.JToggleButton btnTCJ;
    private javax.swing.JToggleButton btnTJ;
    private javax.swing.JToggleButton btnTicket;
    private javax.swing.JToggleButton btnTrator;
    private javax.swing.JToggleButton btnZIG4P1;
    private javax.swing.JToggleButton btnZIG4P2;
    private javax.swing.JToggleButton btnZIG6P0;
    private javax.swing.JToggleButton btnZIG6P1;
    private javax.swing.JToggleButton btnZIG6P2;
    private javax.swing.JToggleButton btnZig34;
    private javax.swing.JToggleButton btnZig35;
    private javax.swing.JToggleButton btnZig36;
    private javax.swing.JToggleButton btnZig3P0;
    private javax.swing.JToggleButton btnZig3P1;
    private javax.swing.JToggleButton btnZig3P2;
    private javax.swing.JToggleButton btnZig3k;
    private javax.swing.JToggleButton btnZig3t;
    private javax.swing.JToggleButton btnZig64;
    private javax.swing.JToggleButton btnZig65;
    private javax.swing.JToggleButton btnZig66;
    private javax.swing.JToggleButton cctManCoor;
    private javax.swing.JCheckBox checkSum;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea taDados;
    private javax.swing.JTextArea taDados1;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField textoDelay;
    private javax.swing.JTextField tfAlto;
    private javax.swing.JTextField tfBaixo;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the zigBeeDevice
     */
    public XBeeDevice getZigBeeDevice() {
        return zigBeeDevice;
    }

    /**
     * @param zigBeeDevice the zigBeeDevice to set
     */
    public void setZigBeeDevice(XBeeDevice zigBeeDevice) {
        this.zigBeeDevice = zigBeeDevice;
    }

    /**
     * @return the mainApp
     */
    public MainApp getMainApp() {
        return mainApp;
    }

    /**
     * @param mainApp the mainApp to set
     */
    public void setMainApp(MainApp mainApp) {
        this.mainApp = mainApp;
    }

    public void startListenner() {

        this.listenner = new IDataReceiveListener() {
            @Override
            public void dataReceived(XBeeMessage xbm) {
                taDados.append("Endereço baixo: " + xbm.getDevice().get16BitAddress());
                taDados.append("\nEndereço alto: " + xbm.getDevice().get64BitAddress() + "\n");

//                System.out.println("Endereço baixo: " + xbm.getDevice().get16BitAddress());
//                System.out.println("Endereço alto: " + xbm.getDevice().get64BitAddress());
                boolean status = xbm.isBroadcast();
                String me = status ? "Recebido broadcast: " : "Recebido unicast: ";
                c = Calendar.getInstance();
                dataHora = ("[" + sdf.format(c.getTime()) + "] - ");
                dataHora = me + dataHora;
                taDados.append(dataHora + xbm.getDataString() + "\n");

                if (me.equals("Recebido unicast: ")) {
                    
                    tfAlto.setText(xbm.getDevice().get64BitAddress().toString());
                    tfBaixo.setText(xbm.getDevice().get16BitAddress().toString());

                }

            }
        };

        mainApp.getxBee().addDataListener(this.listenner);
    }

    public void endListenner() {

        mainApp.getxBee().removeDataListener(listenner);
    }

    public void Atualizar() {
        final long SEGUNDOS = (1000 * 10);// 20 MINUTOS = 1200
        final long DELAY = (1000 * 10);// 1 MINUTOS = 60

        Timer timer = null;
        if (timer == null) {
            timer = new Timer();
            TimerTask tarefa = new TimerTask() {
                @Override
                public void run() {

                    try {

                        XBeeDevice xBee = getMainApp().getxBee();
                        if (xBee == null) {
                            return;
                        }
                        if (xBee.isOpen()) {

                            System.out.println("Conexão está aberta");

                        } else {

                            endListenner();
                            //Capturar porta e velocidade
                            String porta = MainApp.getPORT();
                            int baudrate = MainApp.getBAUD_RATE();

                            XBeeDevice xBee1 = getMainApp().getxBee();
                            getMainApp().setxBee(xBee1);

                            xBee = new XBeeDevice(porta, baudrate);
                            listPorts();
                            if (listPorts() == true) {

                                try {
                                    xBee1.open();

                                    startListenner();
                                } catch (XBeeException e) {
                                    e.printStackTrace();
                                }
                            } else {
                                taDados.append("Porta não reconhecida\n");
                                System.out.println("Porta não reconhecida");
                            }

                        }
                        // Forçar coleta de lixo
                        Runtime.getRuntime().gc();
                    } catch (Exception e) {
                        System.out.println("Não conseguiu conectar");
                        e.printStackTrace();
                    }
                }
            };
            timer.scheduleAtFixedRate(tarefa, DELAY, SEGUNDOS);
        }
    }

    private boolean listPorts() {
        boolean portaIndentificada = false;
        String porta = MainApp.getPORT();
        Enumeration<CommPortIdentifier> portEnum = CommPortIdentifier.getPortIdentifiers();
        while (portEnum.hasMoreElements()) {
            CommPortIdentifier portIdentifier = portEnum.nextElement();
            ArrayList<String> portas = new ArrayList<>();

            portas.add(portIdentifier.getName().toUpperCase());

//            System.out.println("Portas" + portas);
            if (portas.get(0).equals(porta)) {
//                System.out.println("Igual");

                portaIndentificada = true;
            }

        }
        if (portaIndentificada == true) {
            taDados.append("Reconectou\n");
        }
        return portaIndentificada;
    }

    public void enviaComandos() {
        String textoAll = "ZIG35,11976,13A200,415718C2,0,1,0000000400,0000000405,0000000000,2";
        StringTokenizer st = new StringTokenizer(textoAll, "\n");
        while (st.hasMoreTokens()) {

            String texto = st.nextToken();
            dataHora = ("[" + sdf.format(c.getTime()) + "] - ");

            byte[] dataToSend = texto.getBytes();

            try {

                mainApp.getxBee().sendBroadcastData(dataToSend);
                texto = dataHora + texto;
                taDados.append("Enviado broadcast: " + texto + "\n");

                System.out.println(texto);

            } catch (XBeeException ex) {
                Logger.getLogger(ConexaoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
