/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import android.util.Log;
import com.digi.xbee.api.XBeeDevice;
import com.digi.xbee.api.exceptions.XBeeException;
import gnu.io.CommPortIdentifier;
import java.awt.Dialog;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Rafael
 */
public class ConfgXbee extends javax.swing.JFrame {

    private static String PORT;
    private static int BAUD_RATE;
    private MainApp ma;
    public static boolean frmPortaOpened = false;
    private ConexaoFrame conexaoFrame;

    /**
     * Creates new form ConfgXbee
     */
    public ConfgXbee(ConexaoFrame conexFrame) {

        initComponents();
        setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        setLocationRelativeTo(null);
        
        listPorts();

        this.conexaoFrame = conexFrame;
        XBeeDevice xBee = conexFrame.getMainApp().getxBee();

        if (xBee == null) {
            return;
        }

        MainApp auxMainApp = conexFrame.getMainApp();

        cbPort.setSelectedItem(auxMainApp.getPORT().toUpperCase());
        cbVelocidade.setSelectedItem(new Integer(auxMainApp.getBAUD_RATE()));

        //condição para abilitar os botoes se a conexão ja estiver aberta
        if (xBee.isOpen()) {
            this.btnSalvar.setEnabled(false);
        } else {
            this.btnFechar.setEnabled(false);
        }

    }

    private void listPorts()
    {
                
        Enumeration<CommPortIdentifier> portEnum = CommPortIdentifier.getPortIdentifiers();
        while ( portEnum.hasMoreElements() ) 
        {
            CommPortIdentifier portIdentifier = portEnum.nextElement();
            
            cbPort.addItem(portIdentifier.getName().toUpperCase());
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JToggleButton();
        btnSalvar = new javax.swing.JToggleButton();
        cbVelocidade = new javax.swing.JComboBox<>();
        btnFechar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        cbPort = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Selecione a velocidade :");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Selecione a porta :");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete_24x24.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Check_24x24.png"))); // NOI18N
        btnSalvar.setText("Conectar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cbVelocidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9600", "19200", "115200", " " }));

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cancel_24x24.png"))); // NOI18N
        btnFechar.setText("Fechar porta");
        btnFechar.setToolTipText("");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Configuração Xbee");

        cbPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbPortKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(btnFechar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        //obtem a porta selecionada
        String porta = ((String)cbPort.getSelectedItem()).toUpperCase();
        //obtem a velocidade da conexão BAUDRATE
        int baudrate = Integer.parseInt(cbVelocidade.getSelectedItem().toString());

        XBeeDevice xBee = this.conexaoFrame.getMainApp().getxBee();

        xBee = new XBeeDevice(porta, baudrate);

        try {

            xBee.open();
            this.btnSalvar.setEnabled(false);
            this.btnCancelar.setEnabled(true);

            this.conexaoFrame.getMainApp().setxBee(xBee);

            this.conexaoFrame.getMainApp().setPORT(porta);
            this.conexaoFrame.getMainApp().setBAUD_RATE(baudrate);

            conexaoFrame.startListenner();
            
            JOptionPane.showMessageDialog(null, "Conectado com sucesso DataCall");

            this.dispose();

        } catch (XBeeException ex) {

            this.btnSalvar.setEnabled(true);
            this.btnCancelar.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Error: " + ex);

        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        XBeeDevice xBee = this.conexaoFrame.getMainApp().getxBee();
        xBee.close();
        this.btnSalvar.setEnabled(true);
        this.btnCancelar.setEnabled(false);
              
        conexaoFrame.endListenner();
        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(ConfgXbee.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void cbPortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbPortKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvar.doClick();
        }
    }//GEN-LAST:event_cbPortKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnFechar;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JComboBox<String> cbPort;
    private javax.swing.JComboBox<String> cbVelocidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
